In [1]:
import numpy as np
import pandas

In [2]:
m1 = np.array([[5,12,6],[-3,0,14]])
m1

array([[ 5, 12,  6],
       [-3,  0, 14]])

In [11]:
m2 = np.array([[9,8,7],[1,3,5]])
m1.shape

(2, 3)

In [6]:
m1 - m2

array([[-4,  4, -1],
       [-4, -3,  9]])

In [9]:
v1 = np.array([1,2,3])
v2 = np.array([4,5,6])
np.dot(v1,v2)

32

In [31]:
x = np.array([[1,2,3,4,5,],
              [6,7,8,9,10],
              [11,12,13,14,15],
              [16,17,18,19,20],
              [21,22,23,24,25],
              [26,27,28,29,30]])
y = np.array([[6,-1],[8,-4],[2,-2],[7,4],[-6,-9]])
np.dot(x,y)

array([[  26,  -44],
       [ 111, -104],
       [ 196, -164],
       [ 281, -224],
       [ 366, -284],
       [ 451, -344]])

In [14]:
# a = np.array([[1,1,1],[1,1,0],[1,1,1],[0,1,1,],[1,0,1],[0,1,1],[1,0,0]])
a = np.array([[5,21,6],[11,8,62]])
b = np.array([[1,4,2],[0,0,1],[1,0,0]])
c = np.array([[5,6,7],[90,11,32],[5,6,19]])
# c = b.transpose()
np.dot(a,b)+5*c

ValueError: operands could not be broadcast together with shapes (2,3) (3,3) 

In [19]:
c = np.array([['f','i'],['n','p']])
d = np.array([['d','b'],['a','-']])
e = np.dot(a,b)
c_1 = np.array([[1,0],[5,7]])
c_2 = np.array([[0,1],[9,5]])
t = c[0][0]+d[0][1]+c[1][0]+d[0][0]+' '+d[1][0]+'_'+'1'+d[1][1]+d[0][1]+'_'+'1'
print(t)
print(c_1-c_2)

fbnd a_1-b_1
[[-9 -5]
 [-4  2]]


In [6]:
s = np.array([ [[1,2],[3,4]],[[5,6],[7,8]],[[9,10],[11,12]] ])
m = np.array([ [[-2,-2],[3,14]],[[15,-2],[7,8]],[[29,10],[21,32]] ])
l = s[0]+m[1]
l

array([[16,  0],
       [10, 12]])

In [10]:
c_2 = np.array([[3],[2]])
c_3 = np.array([[2],[3]])
np.dot(c_2,c_3)

ValueError: shapes (2,1) and (2,1) not aligned: 1 (dim 1) != 2 (dim 0)

In [13]:
a = np.array([[1,1,4],[1,0,2],[4,2,5]])
b = a.transpose()
c = np.dot(a,b)
c

array([[18,  9, 26],
       [ 9,  5, 14],
       [26, 14, 45]])

In [2]:
old_questions = [
    # 'What is the definition of the following words?: Subset, Empty set, Complement',
    # 'What are the two types of events and how are they determined?',
    # 'What is the conditional probability used for and what does it determine?',
    'Given that P(A│B)>P(B│A) what is the relationship between P(A) and P(B).',
    'What is the conditional probability formula?',
    'What is the additive law denoted as?',
    'What is the multiplication rule denoted as?',
    'Formula for the expected value, variance and probability of possible of the Binomial, Uniform, Poisson,students t.',
    'What is the value that is included in an exponential distribution',
    'What characteristics are shown in the CDF of a exponential distribution',
    # 'What is are independent and dependent events denoted as.',
    # 'What is the formula for the law of total probability?',
    # 'What is the additive law used for?',
    # 'What is the multiplication rule used for?',
    # 'What is bayes theorem used to calculate',
    # 'What is the formula for Bayes theorem?',
    # 'In what field is bayes theorem used in.',
    # 'What are the two types of distributions and their features?',
    # 'How is the type of distribution noted?',
    # 'What is the definition of equiprobable?',
    # 'What are the features of a Bernoulli Distribution?',
    # 'What are the features of a Binomial distribution?',
    # 'What are the features of a Poisson distribution?',
    # 'How is the binomial, bernoulli, logistic, Poisson, exponential, chi-squared, students t and uniform distribution denoted?',
    # 'What is included in the brackets when denoting the previous distributions?',
    # 'How does the graph between a discrete and continuous distribution differ?',
    # 'Where is the normal distribution usually seen?',
    # 'What is the formula for standardization?',
    # 'What is the main difference between the students t distribution and normal distribution?',
    # 'When is the students t distribution used?',
    # 'How is the chi squared distribution calculated?',
    # 'What are the features of the chi squared distribution?',
    # 'What are the features of the exponential distribution?',
    # 'What are the features of the logistic distribution?',
    # 'What is a logistic distribution used for?',
    # 'What is graph called that represents the distribution of the probability called.',
    # 'What is the curve that is created when using a continuous distribution?',
    # 'Explain the reasoning behind the notation: P(x>X)=P(x≥X)',
    # 'What is the cumulative distribution function?',
    # 'What do the following values equate to on a CDF: F(-∞),F(∞)',
    # 'What is the 68,95,99.7 rule?',
    # 'How is the variability calculated when the variability is not given in a normal distribution?',
    # 'How does dividing/ multiplying the affect a normal distribution',
    # 'How does summation affect the graph?',
    # 'What is a standard Normal distribution?',
    # 'If E (y=μ+2.3σ) when not standardized what will the value equal to when standardized.',
    # 'What is the formula for variance for a student’s t distribution?',
    # 'What is the chi-squared distribution used for?',
    # 'How is the expected value and variance calculated for the chi squared distribution?',
    # 'What value does the chi squared distribution start from',
    # 'What is the chi-squared distribution used for in the real world?',
    # 'What distribution do you get when square rooting the chi squared distribution?',
    # 'What are the characteristics of the exponential distribution?',
    # 'What is the formula for the expected value and the variance for the exponential distribution',
    # 'What is one of the most common distributions',
    # 'And how is it transformed into a _____ distribution.',
    # 'What values are recorded in the logistic distribution',
    # 'What is the logistic distribution useful for.',
    # 'What does the CDF of a logistic distribution tell us.',
    # 'What is the formula for the expected value and variance for a logistic distribution.',
    # 'What is the formula for the expected value and variance of a poisson distribution.'
    ]
questions = [
    'Given that P(A│B)>P(B│A) what is the relationship between P(A) and P(B).',
    'What is the conditional probability formula?',
    'What is the additive law denoted as?',
    'What is the multiplication rule denoted as?',
    'Formula for the expected value, variance and probability of possible of the Binomial, Uniform, Poisson,students t.',
    'What is the value that is included in an exponential distribution',
    'What characteristics are shown in the CDF of a exponential distribution',
    'What is the formula for variations, permutations and combinations with and without repetition.',
    'How are the following denoted and what do they mean: Intersection, Union, mutually exclusive.',
    'Given that you draw two cards from a standard deck of cards. Find the probability of getting a spade on the first turn or the second turn.',
    'We have three similar bags B1, B2 and B3 containing 4 balls each. B1 contains 2 red and 2 blue balls, B2 contains 3 red and 1 blue ball and B3 contains 1 red and 3 blue balls. One bag is selected at random, and a ball is selected at random from that bag. What is the probability that the ball is red?',
    'Students in a math class where 40% are males and 60% are females took a test. 50% of the males and 70% of the females passed the test. What percent of students passed the test?',
    'Three factories produce the same tool and supply it to the market. Factory A produces 30% of the tools for the market and the remaining 70% of the tools are produced in factories B and C. 98% of the tools produced in factory A, 95% of the tools produced in factory B and 97% of the tools produced in factory C are not defective. What percent of tools should be produced by factories B and C so that a tool picked at random in the market will have a probability of being non defective equal to 96%?',
    'Five percent of a population have a flu and the remaining 95% do not have this flu. A test is used to detect the flu and this test is positive in 95% of people with a flu and is also (falsely) positive in 1% of the people with no flu. If a person from this population is randomly selected and tested, what is the probability that the test is positive?',
    'On New Years Eve, the probability of a person having a car accident is 0.09. The probability of a person driving while intoxicated is 0.32 and probability of a person having a car accident while intoxicated is 0.15. What is the probability of a person driving while intoxicated or having a car accident?'
    'A basketball player takes 4 independent free throws with a probability of 0.7 of getting a basket on each shot. Let X = the number of baskets he gets. Write out the full probability distribution for X.',
    'If a basketball player takes 8 independent free throws, with a probability of 0.7 of getting a basket on each shot, what is the probability that she gets exactly 6 baskets?, What is the expected number of baskets that she gets?'
    'A student is given a multiple choice exam with 10 questions, each question with five possible answers. He guesses randomly for each question. What’s P(he will get exactly 6 questions correct)? What is the probability he will get at least 6? What is the expected number of correct answers, and what’s the standard deviation?',
    'Suppose that the voting population in Utopia is 300 million and 60% of the voting population intend to vote for Melinda McNulty in the next election. We take a random sample of size 100 from the same voting population and ask each person chosen whether they will vote for Melinda McNulty in the next election or not. Let X be the number of Yesses in our sample. The possible values of X (the number of successes) are 0, 1, 2, 3, · · · , 100. n = 100, p = 0.6, q = 1 − p = 0.4. Calculate the following: (a) What is P(X = 60)? (b) What is P(X 6 20)? (c) What is P(X > 70)? (d) What is P(X < 50)? (e) What is P(50 6 X 6 60)?'

]

b = 1
import random
a = random.sample(range(-1,61), 62)
print(questions[a])

TypeError: list indices must be integers or slices, not list