In [24]:
## Rock, Paper, Scissors

# Import random module for the computer's choice
import random
random.seed = 365

# Mapping of numbers to rock, paper & scissors
int2choice = {0:'R', 1:'P', 2:'S'}

# Class to play the game
class RPS_Game(object):
    
    # Initialize the game
    def __init__(self,num_rounds):
        self.num_rounds = num_rounds # record the total number of rounds
        self.counter_pc_wins = 0     # how many rounds are won by the PC
        self.draws = 0               # how many rounds end in a draw
        print(f"Start of Rock-Paper-Scissors Game - {num_rounds} rounds.")
        
    # The play() method implements the game logic
    def play(self):
        for nr in range(self.num_rounds):
            print(f"It's round No. {nr+1}.")
            user_choice = chr(ord(input("Your Choice: ")) + ord('A') - ord('a'))
            print(user_choice)
            # Validation is required
            while user_choice not in {'R', 'P', 'S'}:
                print("Invalid move. Please enter 'R', 'P' or 'S'.")
                ''' Your code for Question 2 goes here. '''
                                
            # Computer choice
            pc_choice = int2choice[random.randint(0, 2)]
            print(f"Computer's choice: {pc_choice}")
            
            # if
            #
            # elif
            #
            # else:
                
            # Keep track of the game's progress
            print(f"Current result: PC {self.counter_pc_wins} - ",end='')
            print(f"You {nr-self.draws-self.counter_pc_wins}")
            print('-'*30)

## Questions 2 and 6

### Declare an RPS_Game object where 6 instances of RPS are played. Run the game

In [26]:
a = RPS_Game(5)

Start of Rock-Paper-Scissors Game - 5 rounds.


In [12]:
# a = pass
def a():
    for i in range(10):
        pass

In [15]:
from numpy import zeros
def addition(m1,m2):
    result = zeros((3,3))
    for i in range(3):
        for j in range(3):
            result[i][j] = m1[]

In [17]:
print(zeros((3,3)))

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [18]:
a= [[5,3,2],[4,7,1],[6,1,8]]
b= [[5,9,5],[4,1,3],[6,0,8]]

In [22]:
a.append([1,2,3])
for i in range(3):
    b[i].append(i+4)

In [28]:
for i in range(3):
    pass